version: '3.8'

networks:
  instance_net:
    name: ${INSTANCE}_network

services:
  postgres:
    image: postgres:16.2
    container_name: ${INSTANCE}_postgres
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: default
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - instance_net

  mongo:
    image: mongo:latest
    container_name: ${INSTANCE}_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    networks:
      - instance_net

  redis:
    image: redis:latest
    container_name: ${INSTANCE}_redis
    command: [ 'redis-server' ]
    networks:
      - instance_net

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
    container_name: ${INSTANCE}_minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - ~/minio/${INSTANCE}-data:/data
    command: server /data --console-address ":9001"
    networks:
      - instance_net

  backend:
    image: sanreex/chat-artmedia-backend:${TAG}
    container_name: ${INSTANCE}_backend
    environment:
      - PORT=4000
      - WEB_URL=${PUBLIC_URL}
      - MINIO_PUBLIC_ENDPOINT=${PUBLIC_URL}/s3
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - SOCKET_API_KEY=${API_KEY}
      - WIDGET_JWT_SECRET=${WIDGET_JWT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production
      - GMAIL_CLIENT_ID=${GMAIL_CLIENT_ID}
      - GMAIL_CLIENT_SECRET=${GMAIL_CLIENT_SECRET}
      - GMAIL_REFRESH_TOKEN=${GMAIL_REFRESH_TOKEN}
      - TAG=${INSTANCE}
      - SENTRY_DSN=${SENTRY_DSN}
      - DATABASE_URL=postgres://default:${POSTGRES_PASSWORD}@postgres:5432/chatdb
      - MONGODB=${MONGODB}
    expose:
      - '4000'
    depends_on:
      - postgres
      - mongo
      - redis
      - minio
    networks:
      - instance_net

  frontend:
    image: sanreex/chat-artmedia-frontend:${TAG}
    container_name: ${INSTANCE}_frontend
    expose:
      - '80'
    depends_on:
      - backend
    networks:
      - instance_net

  widget-api:
    image: sanreex/chat-artmedia-widget-api:${TAG}
    container_name: ${INSTANCE}_widget_api
    environment:
      - PORT=4001
      - NODE_ENV=production
    expose:
      - '4001'
    depends_on:
      - backend
    networks:
      - instance_net

  socket:
    image: sanreex/chat-artmedia-socket:${TAG}
    container_name: ${INSTANCE}_socket
    environment:
      - PORT=4002
      - NODE_ENV=production
      - API_KEY=${API_KEY}
    expose:
      - '4002'
    depends_on:
      - backend
    networks:
      - instance_net

  gateway:
    image: nginx:alpine
    container_name: ${INSTANCE}_gateway
    ports:
      - "${PORT}:80"
    volumes:
      - ./nginx/generated/${INSTANCE}_default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
      - widget-api
      - socket
    networks:
      - instance_net
